# Generated by Django 2.2 on 2020-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=20)),
                ('vegprice', models.DecimalField(decimal_places=3, max_digits=7)),
                ('nonvegprice', models.DecimalField(decimal_places=3, max_digits=7)),
                ('maxcap', models.IntegerField(blank=True, null=True)),
                ('mincap', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('town', models.ManyToManyField(to='Hotel.City')),
                ('venue', models.ManyToManyField(to='Hotel.VendorType')),
            ],
        ),
    ]
